AGENT_SOURCE = "AGENT_CLI"
PASSED_STATES = {"PASSED", "RECHECKED", "REVIEWED"}
QUEUE_STATUSES = {"WAITING_REVIEW", "NEEDS_REVISION", "RETEST_REQUIRED"}
FOLLOWUP_ALLOWED_STATUSES = {"REVIEWED", "NEEDS_REVISION", "RETEST_REQUIRED", "PASSED", "RECHECKED"}
