import typer

app = typer.Typer(help="StudyFlow 本地学习工作台 CLI")
plan_app = typer.Typer(help="计划与任务")
course_app = typer.Typer(help="课程")
course_answers_app = typer.Typer(help="整课草稿与统一提交")
course_app.add_typer(course_answers_app, name="answers")
submission_app = typer.Typer(help="作答")
review_app = typer.Typer(help="批改")
document_app = typer.Typer(help="文档")
snapshot_app = typer.Typer(help="上下文快照")
task_app = typer.Typer(help="任务")
assignment_app = typer.Typer(help="外部 Agent 待处理队列")
workspace_app = typer.Typer(help="工作区导出与恢复")
app.add_typer(plan_app, name="plan")
app.add_typer(course_app, name="course")
app.add_typer(submission_app, name="submission")
app.add_typer(review_app, name="review")
app.add_typer(document_app, name="document")
app.add_typer(snapshot_app, name="snapshot")
app.add_typer(task_app, name="task")
app.add_typer(assignment_app, name="assignment")
app.add_typer(workspace_app, name="workspace")
